Splits package for Geta.EmailNotification (.NetFramework) and Geta.EmailNotification.Core (.Net 5.0)
Geta/emailnotification pull request #20
Opened 2021-03-05 11:43 UTC by winiarski91

### Changed
- Add Geta.EmailNotification.Common library which holds common interfaces and logic
- Add Geta.EmailNotifications.Core for .Net5.0 projects
- Geta.EmailNotifications is dedicated to .NetFramework projects
- Remove dependencies to log4net

Tested with Epi AlloyKit - NetFramework 4.6.2
![image](https://user-images.githubusercontent.com/9538522/110111051-036b1e80-7db0-11eb-9eae-c89f8ac7422d.png)

Tested with Hello World .Net5.0 application

2021-03-05 17:40 UTC, valdisiljuconoks requested changes

2021-03-05 17:40 UTC, valdisiljuconoks commented on src/Geta.EmailNotification.Common/Geta.EmailNotification.Common.csproj
> +        <Description>Geta.EmailNotification.Common </Description>
please add human readable description :) (+ extra space at the end)

2021-03-05 17:40 UTC, valdisiljuconoks commented on src/Geta.EmailNotification.Common/Geta.EmailNotification.Common.csproj
> +        <Copyright>Copyright Geta© 2021</Copyright>
use "Geta Digital" as company

2021-03-05 17:40 UTC, valdisiljuconoks commented on src/Geta.EmailNotification.Common/Geta.EmailNotification.Common.nuspec
> +        <dependency id="Microsoft.AspNet.Mvc" version="[5.2.7, 5.3)" />
do you need this dependency for common project?

2021-03-05 17:40 UTC, valdisiljuconoks commented on src/Geta.EmailNotification.Common/IMailMessageFactory.cs
> +    public interface IMailMessageFactory
also please include Xml docs for the public types

2021-03-05 17:40 UTC, valdisiljuconoks commented on src/Geta.EmailNotification.Core/Geta.EmailNotification.Core.csproj
> +        <Description>Email notification using SMTP for .Net 5.0</Description>
it's `.NET`

2021-03-05 17:40 UTC, valdisiljuconoks commented on src/Geta.EmailNotification.Core/Geta.EmailNotification.Core.csproj
> +        <PackageVersion>3.0.1</PackageVersion>
should we maybe align all major versions for all packages (at least maybe in this initial .NET5 release)?

2021-03-05 17:40 UTC, valdisiljuconoks commented on src/Geta.EmailNotification.SendGrid/SendGridEmailNotificationClient.cs
> +                    Message = $"Email failed to: {emailsSerialized}. Subject: {request.Subject} Error {ex.Message}."
I know it's not part of this change, but was just wondering aren't you loosing stack trace here?

2021-03-05 17:40 UTC, valdisiljuconoks commented on src/Geta.EmailNotification/EmailNotificationRequest.cs
> +            this.Attachments = new AttachmentCollection();
can't this (or major of these lines) be done already in base class?

2021-03-08 06:58 UTC, winiarski91 commented on src/Geta.EmailNotification.SendGrid/SendGridEmailNotificationClient.cs
> +                    Message = $"Email failed to: {emailsSerialized}. Subject: {request.Subject} Error {ex.Message}."
I think it would be better to have more fields in EmailNotificationResponse. For example new field called Exception which holds full data regarding exception (message, stack trace etc.). Currently stack trace is added to Message

2021-03-08 07:05 UTC, winiarski91 commented on src/Geta.EmailNotification.Core/Geta.EmailNotification.Core.csproj
> +        <PackageVersion>3.0.1</PackageVersion>
As far as I know versions are controlled by TeamCity. It can be change here:
https://tc.geta.no/admin/editProject.html?projectId=GetaPackages_GetaEmailNotification_NuGetGetaEmailNotification&tab=projectParams
It applies for all packages in repository (if I change major version in TC, then all packages Geta.EmailNotification.Common, Geta.EmailNotification.Core will be published with the same version).

2021-03-08 14:49 UTC, valdisiljuconoks commented on src/Geta.EmailNotification.Core/Geta.EmailNotification.Core.csproj
> +        <PackageVersion>3.0.1</PackageVersion>
maybe we should set at least baseline here in csproj file - otherwise it's a bit weird that csproj has 3.x but eventually you get out 4.x at the end of the pipeline :)

2021-03-08 14:50 UTC, valdisiljuconoks submitted a review, later dismissed

2021-03-08 14:50 UTC, valdisiljuconoks commented on src/Geta.EmailNotification.Common/EmailNotificationRequestBase.cs
> +        protected EmailNotificationRequestBase()
you can actually also get rid of this constructor and do:

```
public List<MailboxAddress> To { get; set; } = new List<MailboxAddress>();

```

2021-03-09 10:36 UTC, valdisiljuconoks approved these changes

2021-03-09 11:03 UTC, merged