Fixes #25 missing ViewData
Geta/emailnotification pull request #27
Opened 2021-03-23 07:20 UTC by winiarski91

Removed EmailNotificationRequestBase model. Now EmailNotificationRequest is used and it is shared between all packages. 
Changed ViewData property to Dictionary<string, object> so it can be used in .Net Framework and .Net 5.0 projects

2021-03-23 16:23 UTC, kaspars-ozols requested changes

2021-03-23 16:23 UTC, kaspars-ozols commented on src/Geta.EmailNotification.Core/EmailNotificationRequestBuilder.cs
> -        public EmailNotificationRequestBuilder WithViewModel(object value)
This method allowed to pass in specific view model to the email. IMHO, it is rather important to have it as it is used in quite a few places. 

Instead, should add support and a test case for that.

2021-03-23 16:23 UTC, kaspars-ozols commented on src/Geta.EmailNotification/EmailNotificationRequestBuilder.cs
> -        public EmailNotificationRequestBuilder WithViewModel(object value)
This method allowed to pass in specific view model to the email. IMHO, it is rather important to have it as it is used in quite a few places.

Instead, should add support and a test case for that.

2021-03-23 16:23 UTC, kaspars-ozols commented on src/Geta.EmailNotification/EmailViewRenderer.cs
> +            if (email.ViewData != null)
This will not be null (unless set explicitly) as it has initialization in the `EmailNotificationRequest` model.

2021-03-23 16:23 UTC, kaspars-ozols commented on src/Geta.EmailNotification.Core/EmailViewRenderer.cs
> +                if (email.ViewData != null)
This will not be null (unless set explicitly) as it has initialization in the `EmailNotificationRequest` model.

2021-03-23 16:23 UTC, kaspars-ozols commented on CHANGELOG.md
> +## [4.0.1]
Should bump up the major, if the custom view model support was dropped intentionally (see other comments) as it is a breaking change then.

2021-03-23 16:23 UTC, kaspars-ozols commented on README.md
> +https://github.com/winiarski91
👍

2021-03-24 06:30 UTC, winiarski91 commented on CHANGELOG.md
> +## [4.0.1]
Changed to 5.0.0

2021-03-24 06:37 UTC, winiarski91 commented on src/Geta.EmailNotification/EmailNotificationRequestBuilder.cs
> -        public EmailNotificationRequestBuilder WithViewModel(object value)
Brings back WithViewModel method to EmailNotificationRequestBuilder.

2021-03-24 12:29 UTC, gatisb commented on test/Geta.EmailNotification.Tests/Models/SampleViewModel.cs
> +    public class SampleViewModel
is this actually used in the test, passed in as a model?

2021-03-24 12:30 UTC, gatisb commented on test/Geta.EmailNotification.Tests/Views/Emails/ViewWithSampleViewModel.cshtml
> +@model Geta.EmailNotification.Tests.Models.SampleViewModel
this view is not used in the test

2021-03-24 12:30 UTC, kaspars-ozols approved these changes
👍

2021-03-24 12:31 UTC, gatisb submitted a review, later dismissed
there are two comments would be nice to do them if there is time , but I approve

2021-03-24 12:35 UTC, winiarski91 commented on test/Geta.EmailNotification.Tests/Views/Emails/ViewWithSampleViewModel.cshtml
> +@model Geta.EmailNotification.Tests.Models.SampleViewModel
I didn't commit this code, because we use simple MVC application for "manual" testing of this package. Should I add this code to Geta.EmailNotification.Tests and Geta.EmailNotification.Core.Tests?

2021-03-24 12:35 UTC, gatisb commented on test/Geta.EmailNotification.Tests/Views/Emails/ViewWithSampleViewModel.cshtml
> +@model Geta.EmailNotification.Tests.Models.SampleViewModel
you decide

2021-03-25 06:42 UTC, kaspars-ozols commented on test/Geta.EmailNotification.Tests/Views/Emails/ViewWithSampleViewModel.cshtml
> +@model Geta.EmailNotification.Tests.Models.SampleViewModel
I think it should be part of the tests because specific view model combo is used far more than the view-bag / email-request-as-the-model approach. And it makes sense because people doing MVC are used to do it like this.

2021-03-25 08:24 UTC, winiarski91 commented on test/Geta.EmailNotification.Tests/Views/Emails/ViewWithSampleViewModel.cshtml
> +@model Geta.EmailNotification.Tests.Models.SampleViewModel
Added test case for sending email with custom view model

2021-03-25 08:58 UTC, kaspars-ozols approved these changes

2021-03-25 09:03 UTC, merged